"""create studies tables

Revision ID: a2722167a32c
Revises: 40ab3a189f78
Create Date: 2026-04-07 13:54:03.503896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2722167a32c'
down_revision: Union[str, Sequence[str], None] = '40ab3a189f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('study_type', sa.Enum('OBSERVATIONAL_PROSPECTIVE', 'OBSERVATIONAL_RETROSPECTIVE', 'OBSERVATIONAL_MIXED', name='study_type'), nullable=False),
    sa.Column('data_entry_mode', sa.Enum('MANUAL', 'CSV', 'MANUAL_CSV', name='data_entry_mode'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'IN_ANALYSIS', 'COMPLETED', name='study_status'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('participants_count', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_code'), 'studies', ['code'], unique=True)
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=False)
    op.create_index(op.f('ix_studies_researcher_id'), 'studies', ['researcher_id'], unique=False)
    op.create_table('study_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('parameter_key', sa.Enum('HEART_RATE', 'RESPIRATORY_RATE', 'SPO2', 'TEMPERATURE', name='study_parameter_key'), nullable=False),
    sa.Column('measurement_frequency', sa.Enum('CONTINUOUS', 'EVERY_1_MIN', 'EVERY_5_MIN', 'EVERY_15_MIN', 'EVERY_30_MIN', 'EVERY_1_HOUR', name='measurement_frequency'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_parameters_id'), 'study_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_study_parameters_study_id'), 'study_parameters', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_parameters_study_id'), table_name='study_parameters')
    op.drop_index(op.f('ix_study_parameters_id'), table_name='study_parameters')
    op.drop_table('study_parameters')
    op.drop_index(op.f('ix_studies_researcher_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_code'), table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###
